# Generated by Django 5.2.4 on 2025-07-08 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Arena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arenas', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='PolePlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('arena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pole_placements', to='events.arena')),
                ('pole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.pole')),
            ],
        ),
        migrations.CreateModel(
            name='WingPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('arena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wing_placements', to='events.arena')),
                ('wing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.wings')),
            ],
        ),
    ]
