# Generated by Django 5.2.4 on 2025-07-08 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wingplacement',
            name='arena',
        ),
        migrations.RemoveField(
            model_name='wingplacement',
            name='wing',
        ),
        migrations.CreateModel(
            name='PoleLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('arena', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.arena')),
                ('pole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.pole')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='WingLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('arena', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.arena')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.warehouse')),
                ('wing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.wings')),
            ],
        ),
        migrations.DeleteModel(
            name='PolePlacement',
        ),
        migrations.DeleteModel(
            name='WingPlacement',
        ),
    ]
