# Generated by Django 5.2.4 on 2025-07-08 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_hu', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('number', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=50)),
                ('length', models.FloatField(help_text='Length in meters')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pole_pics/')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poles', to='warehouse.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='Wings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_hu', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('number', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=50)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='wing_pics/')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wings', to='warehouse.warehouse')),
            ],
        ),
    ]
